name: Update GitHub Activity in README

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Actualizar README con la actividad
    permissions:
      contents: write

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Actualizar la sección de actividad
        uses: jamesgeorge007/github-activity-readme@v0.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ Auto-update: Actividad reciente agregada al README"
          MAX_LINES: 5
